name: 'doctl tool installer'
author: 'Joao Correia'
description: 'Install a specific version of doctl binary. Acceptable values are latest or any semantic version string like 1.15.0'
inputs:
  version:
    description: 'Version of doctl'
    required: true
    default: 'latest'
  token:
    description: 'DigitalOcean Access Token'
    required: true
outputs:
  doctl-path:
    description: 'Path to the cached kubectl binary'
branding:
  icon: 'octagon'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/main.js'
